quotes/quote_app/urls.py
from django.urls import path
from . import views

app_name = 'quote_app'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_quote/', views.quote, name='add_quote'),
    path('add_tag/', views.tag, name='add_tag'),
    path('add_author/', views.author, name='add_author'),
    path('detail/<int:author_id>', views.detail, name='detail'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quote_app.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quote_app/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
	name = models.CharField(max_length=75, null=False, unique=True)

	def __str__(self):
		return f"{self.name}"


class Author(models.Model):
	fullname = models.CharField(max_length=50, null=False, unique=True)
	born = models.CharField(max_length=100, default="born")
	description = models.CharField(max_length=5000, default="description")

	def __str__(self):
		return f"{self.fullname}"


class Quote(models.Model):
	text = models.CharField(max_length=1500, null=False, unique=True)
	tags = models.ManyToManyField(Tag)
	author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)

	def __str__(self):
		return f"{self.text}"

quotes/quote_app/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Quote, Author


class TagForm(ModelForm):
	name = CharField(min_length=3, max_length=30, required=True, widget=TextInput())

	class Meta:
		model = Tag
		fields = ['name']


class QuoteForm(ModelForm):

	text = CharField(min_length=5, max_length=250, required=True, widget=TextInput())

	class Meta:
		model = Quote
		fields = ['text']
		exclude = ['tags', 'author']


class AuthorForm(ModelForm):
	fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
	born = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
	description = CharField(min_length=3, max_length=5000, required=True, widget=TextInput())

	class Meta:
		model = Author
		fields = ['fullname', 'born', 'description']

quotes/quote_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author

# Create your views here.


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quote_app/index.html', {"quotes": quotes})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quote_app:main')
        else:
            return render(request, 'quote_app/add_author.html', {'form': form})

    return render(request, 'quote_app/add_author.html', {'form': AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            author = Author.objects.filter(fullname__in=request.POST.getlist('authors'))
            new_note.author = author[0]
            new_note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='quote_app:main')
        else:
            return render(request, 'quote_app/add_quote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'quote_app/add_quote.html', {"tags": tags, "authors": authors, 'form': QuoteForm()})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quote_app:main')
        else:
            return render(request, 'quote_app/add_tag.html', {'form': form})

    return render(request, 'quote_app/add_tag.html', {'form': TagForm()})


@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quote_app:main')


def detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quote_app/detail.html', {"author": author})

quotes/quote_app/templates/quote_app/add_author.html
{% extends "quote_app/base.html" %}

{% block content %}
<h1 style="text-align:center;">Add author</h1>
<div class="container">
    <div class="row justify-content-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="mb-3">
                    <label for="author_fullname" class="form-label"></label>
                    <input type="text" id="author_fullname" name="fullname" class="form-control" placeholder="Author fullname">
                    <span>{{ form.errors.name }}</span>
                </div>
                <div class="mb-3">
                    <input type="text" id="disabledTextInput" class="form-control" placeholder="Disabled input">
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Username</label>
                        {{ form.username }}
                    </div>
                    <span>{{ form.errors.username }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email</label>
                        {{ form.email}}
                    </div>
                    <span>{{ form.errors.email }}</span>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Password</label>
                        {{ form.password1 }}
                    </div>
                    <span>{{ form.errors.password1 }}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Confirm password</label>
                        {{ form.password2 }}
                    </div>
                    <span>{{ form.errors.password2 }}</span>
                </div>
            </div>
            <div class="form-group mt-4 mb-1">
                <button type="submit" class="btn btn-success">Sign up</button>
                <button type="reset" class="secondary">Reset</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

quotes/quote_app/templates/quote_app/add_quote.html
{% extends "quote_app/base.html" %}

{% block content %}
<h1 style="text-align:center;">Add quote</h1>

<form method="POST" action="{% url 'quote_app:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="authors" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="form-group mt-4 mb-1 ">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>


{% endblock %}

quotes/quote_app/templates/quote_app/add_tag.html
{% extends "quote_app/base.html" %}

{% block content %}
<h1 style="text-align:center;">Add tag</h1>
{% csrf_token %}
<div class="container">
    <div class="row justify-content-center">
        <form method="post" action="{% url 'quote_app:add_tag' %}">
            {% csrf_token %}
            <div class="form-row mt-3">
                <div class="mb-3">
                    <label for="tag_name" class="form-label">Enter tag name:</label>

                    <input type="text" id="tag_name" name="name" class="form-control" placeholder="Tag name">

                    <span>{{ form.errors.name }}</span>
                </div>

            </div>

            <div class="form-group mt-4 mb-1 ">
                <button type="submit" class="btn btn-success">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

</form>

{% endblock %}

quotes/quote_app/templates/quote_app/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>PythonGuides</title>
</head>

<body>
<nav class="navbar navbar-expand-sm navbar-light bg-info shadow">
    <a class="navbar-brand" href="/">
        Encore
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/products">Products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" ">Contact</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Add
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'quote_app:add_quote' %}">Add quote</a>
                    <a class="dropdown-item" href="{% url 'quote_app:add_tag' %}">Add tag</a>
                    <a class="dropdown-item" href="{% url 'quote_app:add_author' %}">Add author</a>
                </div>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <a class="text-dark" href="{% url 'users:logout' %}">Logout</a>
        <a class="btn btn-sm btn-outline-primary m-2" href=" ">{{user.username|title}}</a>
        {% else %}
        <a class="text-dark" href="{% url 'users:login' %}">Login</a>
        <a class="btn btn-sm btn-primary m-2" href="{% url 'users:signup' %}">Sigh up</a>
        {% endif %}
    </div>
</nav>

<div class="container my-3">
    <h2 style="text-align:center;">Quotes</h2>
</div>
{% block content %}{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

quotes/quote_app/templates/quote_app/detail.html
{% extends "quote_app/base.html" %}
{% block content %}

<h1>{{author.fullname}}</h1>
<h2>Born: <small>{{author.born}}</small></h2>
<h2>Description: <small>{{author.description}}</small></h2>

{% endblock %}

quotes/quote_app/templates/quote_app/index.html
{% extends "quote_app/base.html" %}
{% load extract_tags %}
{% block content %}
<h1 style="text-align:center;">Main page</h1>
{% for quote in quotes %}
<ul>
    <li>
        <h3>{{ quote.text }}</h3>
        <p>Author: {{ quote.author }}</p>
        <a href="{% url 'quote_app:detail' quote.author.id %}" role="button" class="contrast">about author</a>

        <p>Tags: <small> {{ quote.tags|tags }} </small></p>

        <a href="{% url 'quote_app:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
    </li>
</ul>
{% endfor %}
{% endblock %}